  [
    {
        "id": "cart-1",
        "type": "bed",
        "name": "Milan Lucino",
        "images": [
            "https://matras32.ru/icache/i/www.mebhome.ru/imgup/97186_0.jpg",
            "https://unison24.ru/image/catalog/tovary/krovati/ormatek/castello/krovat-ormatek-castello-tkan-bentlej_1.jpg",
            "https://vn-74.ru/image/cache/data/catalog6/podushka-leb-puh-slavtextile-500x500.jpg",
            "https://kayrosblog.ru/wp-content/uploads/2018/06/Kak-delayut-ortopedicheskoe-osnovanie-dlya-krovati-4.jpg",
            "http://rina-mebel.ru/uploadedFiles/eshopimages/big/krovat_tokio_4.jpg"
        ],
        "kant": true,
        "mechanizm": false,
        "length": 900,
        "frame": "дуб",
        "legs": "дерево",
        "carriage_screed": false,
        "fluff": "синтетика",
        "rack_bottom": "фанера",
        "headboard": false,
        "tsarga": true,
        "massive_frame": "МДф",
        "cloth": "шенил"
    },
    {
        "id": "cart-2",
        "type": "bed",
        "name": "Paris",
        "images": [
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-141277917959653700.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-143522747837328400.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-146969223192351000.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-143522745829054700.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-143522745829087200.jpeg"
        ],
        "kant": true,
        "mechanizm": true,
        "length": 1400,
        "frame": "бук",
        "legs": "металическая2",
        "carriage_screed": true,
        "fluff": "гусиный",
        "rack_bottom": "стандарт",
        "headboard": "стандарт",
        "tsarga": true,
        "massive_frame": "Дуб",
        "cloth": "велюр"
    },
    {
        "id": "cart-3",
        "type": "bed",
        "name": "leonardo da Vinci",
        "images": [
            "https://mnogosna.ru/images/products/product_add_pic_29481.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29482.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29483.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29484.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29431.jpg"
        ],
        "kant": true,
        "mechanizm": true,
        "length": 1800,
        "frame": "орех",
        "legs": "металическая1",
        "carriage_screed": true,
        "headboard": "ушки",
        "tsarga": false,
        "fluff": "синтетика",
        "rack_bottom": "ортопедическое",
        "massive_frame": "МДф",
        "cloth": "рогожка"
    },
    {
        "id": "cart-4",
        "name": "Mona Lisa",
        "type": "bed",
        "images": [
            "https://mnogosna.ru/images/products/product_img_9965.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16432.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16429.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16430.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16431.jpg"
        ],
        "kant": true,
        "mechanizm": false,
        "length": 1400,
        "frame": "дуб",
        "legs": "металическая1",
        "carriage_screed": false,
        "headboard": "наборные_панелями",
        "tsarga": false,
        "fluff": "синтетика",
        "rack_bottom": "ортопедическое",
        "massive_frame": "МДф",
        "cloth": "рогожка"
    },
    {
        "id": "cart-5",
        "name": "Panda",
        "type": "sofa",
        "images": [
            "https://valles.top/upload/iblock/50d/50d812974d9418810e23aebb9205d1e4.jpeg",
            "https://valles.top/upload/iblock/bda/bda83b7f5ff738c043cad65be5937256.jpeg",
            "https://valles.top/upload/iblock/3dc/3dc84be1dec589cb664a8d6883351929.jpeg",
            "https://valles.top/upload/iblock/118/1180eec06cd6e4c0d0c66bb07161b47b.jpeg",
            "https://valles.top/upload/iblock/25e/25e28b906a1acbfec5e438ab9e882527.jpg"
        ],
        "width": 850,
        "rhomb": false,
        "configuration": "прямой",
        "rules_armrest": false,
        "armrest": true,
        "kant": true,
        "frame_base": "металлокаркас",
        "fluff": "натуральный",
        "foam": "средний",
        "material_complex": "простая",
        "mechanizm": "отелло",
        "legs": "металлическая2",
        "thickness_back": 200,
        "thickness_pillow": 200,
        "thickness_armret": 50,
        "carriage_screed": true,
        "backsplash": false,
        "cloth": "рогожка",
        "cloth_base": 0.22,
        "cloth_armrest": 2.4,
        "cloth_back": 0.3
    },
    {
        "id": "cart-6",
        "name": "Mariya",
        "type": "sofa",
        "images": [
            "https://mebilar.ru/wa-data/public/shop/products/54/17/1754/images/8821/Mirta_uglovoy_2500render.970.jpg",
            "https://mebilar.ru/wa-data/public/shop/products/54/17/1754/images/8822/Polite_316_bezhevyy_lilii_kant-temnyy_.970.jpg",
            "https://mebilar.ru/wa-data/public/shop/products/54/17/1754/images/8823/Uglovoy-divan-garmoniya-tsveta-2-Mirta-levyy-tkan-bezhevyy-podushki-lilii-TD-300-1-mekhanizm-transformatsii-delfin.970.jpg",
            "https://valles.top/upload/iblock/25e/25e28b906a1acbfec5e438ab9e882527.jpg",
            "https://valles.top/upload/iblock/118/1180eec06cd6e4c0d0c66bb07161b47b.jpeg"
        ],
        "width": 900,
        "rhomb": true,
        "configuration": "угловой",
        "rules_armrest": false,
        "armrest": true,
        "kant": false,
        "frame_base": "массив_рамы",
        "fluff": "синтетика",
        "foam": "мягкий",
        "material_complex": "сложная",
        "mechanizm": "французская",
        "legs": false,
        "thickness_back": 150,
        "thickness_pillow": 120,
        "thickness_armret": 270,
        "carriage_screed": true,
        "backsplash": true,
        "cloth": "шенил",
        "cloth_base": 0.27,
        "cloth_armrest": 2.1,
        "cloth_back": 0.25
    },
    {
        "id": "cart-7",
        "name": "Irina",
        "type": "sofa",
        "images": [
            "https://asmdivan.ru/images/0002/0094.jpg",
            "https://asmdivan.ru/images/0002/0091.jpg",
            "https://asmdivan.ru/images/0002/0061.jpg",
            "https://asmdivan.ru/images/0002/0097.jpg",
            "https://asmdivan.ru/images/0002/0073.jpg"
        ],
        "width": 1020,
        "configuration": "угловой_с_оттоманкой",
        "rules_armrest": false,
        "rhomb": false,
        "armrest": true,
        "kant": true,
        "frame_base": "массив_рамы",
        "fluff": "синтетика",
        "foam": "средний",
        "material_complex": "простая",
        "mechanizm": "пантограф",
        "legs": "деревянная",
        "thickness_back": 270,
        "thickness_pillow": 150,
        "thickness_armret": 120,
        "carriage_screed": false,
        "backsplash": true,
        "cloth": "велюр",
        "cloth_base": 0.22,
        "cloth_armrest": 1.7,
        "cloth_back": 0.3
    }
]
