[
    {
        "id": "cart-1",
        "type": "bed",
        "name": "Milan Lucino",
        "images": [
            "https://matras32.ru/icache/i/www.mebhome.ru/imgup/97186_0.jpg",
            "https://unison24.ru/image/catalog/tovary/krovati/ormatek/castello/krovat-ormatek-castello-tkan-bentlej_1.jpg",
            "https://vn-74.ru/image/cache/data/catalog6/podushka-leb-puh-slavtextile-500x500.jpg",
            "https://kayrosblog.ru/wp-content/uploads/2018/06/Kak-delayut-ortopedicheskoe-osnovanie-dlya-krovati-4.jpg",
            "http://rina-mebel.ru/uploadedFiles/eshopimages/big/krovat_tokio_4.jpg"
        ],
        "кант": true,
        "механизм": false,
        "length": 900,
        "рама": "дуб",
        "ножки": "дерево",
        "каретная_стяжка": false,
        "пух": "синтетика",
        "реечное_дно": "фанера",
        "изголовье": false,
        "царга": true,
        "массивная_рама": "МДф",
        "ткань": "шенил"
    },
    {
        "id": "cart-2",
        "type": "bed",
        "name": "Paris",
        "images": [
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-141277917959653700.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-143522747837328400.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-146969223192351000.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-143522745829054700.jpeg",
            "https://www.vashmatrass.ru/files/images/ecommerce/bigproduct-143522745829087200.jpeg"
        ],
        "кант": true,
        "механизм": true,
        "length": 1400,
        "рама": "бук",
        "ножки": "металическая2",
        "каретная_стяжка": true,
        "пух": "гусиный",
        "реечное_дно": "стандарт",
        "изголовье": "стандарт",
        "царга": true,
        "массивная_рама": "Дуб",
        "ткань": "велюр"
    },
    {
        "id": "cart-3",
        "type": "bed",
        "name": "leonardo da Vinci",
        "images": [
            "https://mnogosna.ru/images/products/product_add_pic_29481.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29482.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29483.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29484.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_29431.jpg"
        ],
        "кант": true,
        "механизм": true,
        "length": 1800,
        "рама": "орех",
        "ножки": "металическая1",
        "каретная_стяжка": true,
        "изголовье": "ушки",
        "царга": false,
        "пух": "синтетика",
        "реечное_дно": "ортопедическое",
        "массивная_рама": "МДф",
        "ткань": "рогожка"
    },
    {
        "id": "cart-4",
        "name": "Mona Lisa",
        "type": "bed",
        "images": [
            "https://mnogosna.ru/images/products/product_img_9965.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16432.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16429.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16430.jpg",
            "https://mnogosna.ru/images/products/product_add_pic_16431.jpg"
        ],
        "кант": true,
        "механизм": false,
        "length": 1400,
        "рама": "дуб",
        "ножки": "металическая1",
        "каретная_стяжка": false,
        "изголовье": "наборные_панелями",
        "царга": false,
        "пух": "синтетика",
        "реечное_дно": "ортопедическое",
        "массивная_рама": "МДф",
        "ткань": "рогожка"
    },
    {
        "id": "cart-5",
        "name": "Panda",
        "type": "sofa",
        "images": [
            "https://valles.top/upload/iblock/50d/50d812974d9418810e23aebb9205d1e4.jpeg",
            "https://valles.top/upload/iblock/bda/bda83b7f5ff738c043cad65be5937256.jpeg",
            "https://valles.top/upload/iblock/3dc/3dc84be1dec589cb664a8d6883351929.jpeg",
            "https://valles.top/upload/iblock/118/1180eec06cd6e4c0d0c66bb07161b47b.jpeg",
            "https://valles.top/upload/iblock/25e/25e28b906a1acbfec5e438ab9e882527.jpg"
        ],
        "ширина": 850,
        "ромбик": false,
        "configuration": "прямой",
        "rules_armrest": false,
        "armrest": true,
        "кант": true,
        "основание_рамы": "металлокаркас",
        "пух": "натуральный",
        "ппу": "средний",
        "механизм": "отелло",
        "ножки": "металлическая2",
        "толщина_спинки": 200,
        "толщина_подушек": 200,
        "толщина_подлокотника": 50,
        "каретная_стяжка": true,
        "отстрочка": false,
        "ткань": "рогожка",
        "ткань_основание": 0.22,
        "ткань_подлокотник": 2.4,
        "ткань_спинка": 0.3
    },
    {
        "id": "cart-6",
        "name": "Mariya",
        "type": "sofa",
        "images": [
            "https://mebilar.ru/wa-data/public/shop/products/54/17/1754/images/8821/Mirta_uglovoy_2500render.970.jpg",
            "https://mebilar.ru/wa-data/public/shop/products/54/17/1754/images/8822/Polite_316_bezhevyy_lilii_kant-temnyy_.970.jpg",
            "https://mebilar.ru/wa-data/public/shop/products/54/17/1754/images/8823/Uglovoy-divan-garmoniya-tsveta-2-Mirta-levyy-tkan-bezhevyy-podushki-lilii-TD-300-1-mekhanizm-transformatsii-delfin.970.jpg",
            "https://valles.top/upload/iblock/25e/25e28b906a1acbfec5e438ab9e882527.jpg",
            "https://valles.top/upload/iblock/118/1180eec06cd6e4c0d0c66bb07161b47b.jpeg"
        ],
        "ширина": 900,
        "ромбик": true,
        "configuration": "угловой",
        "rules_armrest": false,
        "armrest": true,
        "кант": false,
        "основание_рамы": "массив_рамы",
        "пух": "синтетика",
        "ппу": "мягкий",
        "механизм": "французская",
        "ножки": "металлическая",
        "толщина_спинки": 150,
        "толщина_подушек": 120,
        "толщина_подлокотника": 270,
        "каретная_стяжка": true,
        "отстрочка": true,
        "ткань": "шенил",
        "ткань_основание": 0.27,
        "ткань_подлокотник": 2.1,
        "ткань_спинка": 0.25
    },
    {
        "id": "cart-7",
        "name": "Irina",
        "type": "sofa",
        "images": [
            "https://asmdivan.ru/images/0002/0094.jpg",
            "https://asmdivan.ru/images/0002/0091.jpg",
            "https://asmdivan.ru/images/0002/0061.jpg",
            "https://asmdivan.ru/images/0002/0097.jpg",
            "https://asmdivan.ru/images/0002/0073.jpg"
        ],
        "ширина": 1020,
        "configuration": "угловой_с_оттоманкой",
        "rules_armrest": false,
        "ромбик": false,
        "armrest": true,
        "кант": true,
        "основание_рамы": "массив_рамы",
        "пух": "синтетика",
        "ппу": "средний",
        "механизм": "пантограф",
        "ножки": "деревянная",
        "толщина_спинки": 270,
        "толщина_подушек": 150,
        "толщина_подлокотника": 120,
        "каретная_стяжка": false,
        "отстрочка": true,
        "ткань": "велюр",
        "ткань_основание": 0.22,
        "ткань_подлокотник": 1.7,
        "ткань_спинка": 0.3
    }
]
